name: qprompt
base: core24
version: '2.0.0'
summary: Personal teleprompter software # 79 char long summary
description: |
  Personal teleprompter software for all video creators.
  Built with ease of use, productivity, control accuracy, and
  smooth performance in mind. QPrompt works with tablet teleprompters,
  studio teleprompters, webcams and cellphones.
license: GPL-3.0

type: app
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
# grade: devel # must be 'stable' to release into candidate/stable channels
# confinement: devmode # use 'strict' once you have the right plugs and slots
compression: lzo
icon: snap/gui/icon.png

platforms:
    amd64:
        build-on: [amd64]
        build-for: [amd64]

parts:
  qprompt:
    after:
    - qhotkey
    parse-info:
    - usr/share/metainfo/com.cuperino.qprompt.appdata.xml
    plugin: cmake
    source: https://github.com/Cuperino/QPrompt.git
    source-type: git
    source-tag: 2.0.0-snap
    cmake-parameters:
    - -DKDE_INSTALL_USE_QT_SYS_PATHS=ON
    - -DCMAKE_INSTALL_PREFIX=/usr
    - -DCMAKE_BUILD_TYPE=Release
    - -DENABLE_TESTING=OFF
    - -DBUILD_TESTING=OFF
    - -DSOURCE_DEPENDENCIES_EXCLUSIVELY_FROM_SYSTEM=ON
    build-snaps:
    - core24
    - kf6-core24
    build-packages:
    - kirigami2-dev
    - libgl-dev
    prime:
    - -usr/lib/*/cmake/*
    - -usr/include/*
    - -usr/share/ECM/*
    - -usr/share/man/*
    - -usr/bin/X11
    - -usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0
    - -usr/lib/aspell/*
    - -usr/share/lintian

  qhotkey:
    plugin: cmake
    source: https://github.com/Skycoder42/QHotkey.git
    source-type: git
    source-branch: master
    cmake-parameters:
    - -DCMAKE_INSTALL_PREFIX=/usr
    - -DCMAKE_BUILD_TYPE=Release
    - -DBUILD_SHARED_LIBS=ON
    - -DQT_DEFAULT_MAJOR_VERSION=6
    build-snaps:
    - core24
    - kf6-core24
    prime:
    - -usr/lib/*/cmake/*
    - -usr/include/*
    - -usr/share/ECM/*
    - -usr/share/man/*
    - -usr/bin/X11
    - -usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0
    - -usr/lib/aspell/*
    - -usr/share/lintian

apps:
  qprompt:
    extensions:
      - kde-neon-6
    common-id: com.cuperino.qprompt.desktop
    command: usr/bin/qprompt
    plugs:
      - desktop
      - desktop-legacy
      - opengl
      - wayland
      - x11
      - home
      - removable-media
      - network
