name: qprompt
title: QPrompt Teleprompter
base: core26
version: '2.0.2'
summary: Personal teleprompter software # 79 char long summary
description: |
  Personal teleprompter software for all video creators.
  Built with ease of use, productivity, control accuracy, and
  smooth performance in mind. QPrompt works with tablet teleprompters,
  studio teleprompters, webcams and cellphones.
license: GPL-3.0
contact: https://forum.qprompt.app/
issues: https://feedback.qprompt.app/
source-code: https://github.com/Cuperino/QPrompt-Teleprompter/
website: https://qprompt.app/

type: app
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
# grade: devel # must be 'stable' to release into candidate/stable channels
# confinement: devmode # use 'strict' once you have the right plugs and slots
compression: lzo
icon: snap/gui/icon.png

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

parts:
  qprompt:
    after:
    - qhotkey
    parse-info:
    - usr/share/metainfo/com.cuperino.qprompt.appdata.xml
    plugin: cmake
    source: https://github.com/Cuperino/QPrompt-Teleprompter.git
    source-type: git
    source-tag: v2.0.2-no-screens
    cmake-parameters:
    - -DKDE_INSTALL_USE_QT_SYS_PATHS=ON
    - -DCMAKE_INSTALL_PREFIX=/usr
    - -DCMAKE_BUILD_TYPE=Release
    - -DENABLE_TESTING=OFF
    - -DBUILD_TESTING=OFF
    - -DSOURCE_DEPENDENCIES_EXCLUSIVELY_FROM_SYSTEM=ON
    build-snaps:
    - core26
    build-packages:
    - extra-cmake-modules
    - kirigami2-dev
    - libduktape207
    - libgl-dev
    - libkf6breezeicons-dev
    - libkf6coreaddons-dev
    - libkirigami-dev
    - libkf6crash-dev
    - libkf6iconthemes-dev
    - qt6-tools-dev
    - qt6-shadertools-dev
    - qt6-svg-dev
    - qt6-l10n-tools
    prime:
    - -usr/lib/*/cmake/*
    - -usr/include/*
    - -usr/share/ECM/*
    - -usr/share/man/*
    - -usr/bin/X11
    - -usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0
    - -usr/lib/aspell/*
    - -usr/share/lintian
    stage-packages:
    - hicolor-icon-theme
    - kf6-breeze-icon-theme
    - libkf6coreaddons6
    - libkf6crash6
    - libkf6iconthemes6
    - libkirigami6
    - libqt6svg6
    - libqt6qmlworkerscript6
    - libqt6shadertools6
    - qml6-module-org-kde-kirigami
    - qml6-module-qt-labs-platform
    - qml6-module-qtqml
    - qml6-module-qtqml-models
    - qml6-module-qtqml-statemachine
    - qml6-module-qtquick-controls
    - qml6-module-qtcore
    - qml6-module-qt-labs-settings
    - qml6-module-qtquick-dialogs
    - qml6-module-qtquick-shapes
    - qt6-svg-plugins
    - qt6-translations-l10n
    # Dependencies provided by KDE neon SDK
    - libproxy1v5
    - libqt6gui6
    - qt6-wayland

  qhotkey:
    plugin: cmake
    source: https://github.com/Skycoder42/QHotkey.git
    source-type: git
    source-branch: master
    cmake-parameters:
    - -DCMAKE_INSTALL_PREFIX=/usr
    - -DCMAKE_BUILD_TYPE=Release
    - -DBUILD_SHARED_LIBS=ON
    - -DQT_DEFAULT_MAJOR_VERSION=6
    build-snaps:
    - core26
    prime:
    - -usr/lib/*/cmake/*
    - -usr/include/*
    - -usr/share/ECM/*
    - -usr/share/man/*
    - -usr/bin/X11
    - -usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0
    - -usr/lib/aspell/*
    - -usr/share/lintian

  gpu-2604:
    after:
    - qprompt
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2604-cleanup mesa-2604
    prime:
    - bin/gpu-2604-wrapper

plugs:
  dot-config-cuperino-qprompt:
    interface: personal-files
    read:
    - $HOME/.config/Cuperino/qprompt.conf
  gpu-2604:
    interface: content
    target: $SNAP/gpu-2604
    default-provider: mesa-2604

apps:
  qprompt:
    common-id: com.cuperino.qprompt.desktop
    command-chain:
    - bin/gpu-2604-wrapper
    command: usr/bin/qprompt
    environment:
      # Path needed for libproxy to be found
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy
      QT_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins
      QML_IMPORT_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/qml
      QML2_IMPORT_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/qml
      XDG_DATA_DIRS: $SNAP/usr/share:$XDG_DATA_DIRS
    plugs:
    - desktop
    - desktop-legacy
    - opengl
    - wayland
    - x11
    - home
    - removable-media
    - network
    - dot-config-cuperino-qprompt
