name: qprompt
base: core22
version: '1.1.6'
summary: Personal teleprompter software # 79 char long summary
description: |
  Personal teleprompter software for all video creators.
  Built with ease of use, productivity, control accuracy, and
  smooth performance in mind. QPrompt works with tablet teleprompters,
  studio teleprompters, webcams and cellphones.
license: GPL-3.0

type: app
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
# grade: devel # must be 'stable' to release into candidate/stable channels
# confinement: devmode # use 'strict' once you have the right plugs and slots
compression: lzo
icon: snap/gui/icon.png

architectures:
- build-on: amd64
  build-for: amd64
- build-on: arm64
  build-for: arm64

parts:
  qprompt:
    after:
    - qhotkey
    parse-info:
    - usr/share/metainfo/com.cuperino.qprompt.appdata.xml
    plugin: cmake
    source: https://github.com/Cuperino/QPrompt.git
    source-type: git
    source-tag: v1.1.6-snap
    cmake-parameters:
    - "-DCMAKE_INSTALL_PREFIX=/usr"
    - "-DCMAKE_BUILD_TYPE=Release"
    - "-DENABLE_TESTING=OFF"
    - "-DBUILD_TESTING=OFF"
    - "-DKDE_SKIP_TEST_SETTINGS=ON"
    build-packages:
    - extra-cmake-modules
    - libqt5svg5-dev
    - libqt5x11extras5-dev
    - libkf5coreaddons-dev
    - libkf5i18n-dev
    - libkf5crash-dev
    - kirigami2-dev
    - libgl-dev
    stage-packages:
    - libqt5svg5
    - libqt5x11extras5
    - libkf5coreaddons5
    - libkf5i18n5
    - libkf5crash5
    - libkf5kirigami2-5
    - qml-module-qt-labs-platform
    - qml-module-qtqml
    - qml-module-qtqml-models2
    - qml-module-qtqml-statemachine
    - qml-module-qtquick-controls
    - qml-module-qtquick-controls2
    - qml-module-qtquick-dialogs
    - qml-module-qtquick-shapes
    - qml-module-org-kde-kirigami2

  qhotkey:
    plugin: cmake
    source: https://github.com/Skycoder42/QHotkey.git
    source-type: git
    source-branch: master

apps:
  qprompt:
    common-id: com.cuperino.qprompt.desktop
    command: usr/bin/qprompt
    plugs:
      - desktop
      - desktop-legacy
      - opengl
      - wayland
      - home
      - removable-media
      - network
